xml = """
    <response>
    <header>
    <resultCode/>
    <resultMsg/>
    </header>
    <body>
    <items>
    <trademarkDesignationGoodstInfo>
    <DesignationGoodsSerialNumber>0</DesignationGoodsSerialNumber>
    <DesignationGoodsClassificationInformationCode>010(010류)</DesignationGoodsClassificationInformationCode>
    <SimilargroupCode>G2401</SimilargroupCode>
    <DesignationGoodsHangeulName>대사성약제</DesignationGoodsHangeulName>
    <DesignationGoodsEnglishsentenceName></DesignationGoodsEnglishsentenceName>
    </trademarkDesignationGoodstInfo>
    <trademarkDesignationGoodstInfo>
    <DesignationGoodsSerialNumber>1</DesignationGoodsSerialNumber>
    <DesignationGoodsClassificationInformationCode>010(010류)</DesignationGoodsClassificationInformationCode>
    <SimilargroupCode>G1004</SimilargroupCode>
    <DesignationGoodsHangeulName>제초제</DesignationGoodsHangeulName>
    <DesignationGoodsEnglishsentenceName></DesignationGoodsEnglishsentenceName>
    </trademarkDesignationGoodstInfo>
    <trademarkDesignationGoodstInfo>
    <DesignationGoodsSerialNumber>2</DesignationGoodsSerialNumber>
    <DesignationGoodsClassificationInformationCode>010(010류)</DesignationGoodsClassificationInformationCode>
    <SimilargroupCode>G1004</SimilargroupCode>
    <DesignationGoodsHangeulName>소화기관용약제</DesignationGoodsHangeulName>
    <DesignationGoodsEnglishsentenceName></DesignationGoodsEnglishsentenceName>
    </trademarkDesignationGoodstInfo>
    <trademarkDesignationGoodstInfo>
    <DesignationGoodsSerialNumber>3</DesignationGoodsSerialNumber>
    <DesignationGoodsClassificationInformationCode>010(010류)</DesignationGoodsClassificationInformationCode>
    <SimilargroupCode>G1004</SimilargroupCode>
    <DesignationGoodsHangeulName>순환기관용약제</DesignationGoodsHangeulName>
    <DesignationGoodsEnglishsentenceName></DesignationGoodsEnglishsentenceName>
    </trademarkDesignationGoodstInfo>
    <trademarkDesignationGoodstInfo>
    <DesignationGoodsSerialNumber>4</DesignationGoodsSerialNumber>
    <DesignationGoodsClassificationInformationCode>010(010류)</DesignationGoodsClassificationInformationCode>
    <SimilargroupCode>G1004</SimilargroupCode>
    <DesignationGoodsHangeulName>중추신경계용약제</DesignationGoodsHangeulName>
    <DesignationGoodsEnglishsentenceName></DesignationGoodsEnglishsentenceName>
    </trademarkDesignationGoodstInfo>
    </items>
    </body>
    </response>
"""